services:
  - type: redis
    name: redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0  # keep open; tighten later if desired

  - type: web
    name: ingest
    env: docker
    dockerfilePath: services/ingest/Dockerfile
    plan: free
    # healthCheckPath: /
    envVars:
      - key: REDIS_URL
        fromService: { type: redis, name: redis, property: connectionString }
      - key: LANGFUSE_HOST
        sync: false
      - key: LANGFUSE_PUBLIC_KEY
        sync: false
      - key: LANGFUSE_SECRET_KEY
        sync: false
      - key: LANGFUSE_TRACING_ENVIRONMENT
        value: render

  - type: web
    name: embeddings
    env: docker
    dockerfilePath: services/embeddings/Dockerfile
    plan: free
    # healthCheckPath: /
    envVars:
      - key: REDIS_URL
        fromService: { type: redis, name: redis, property: connectionString }
      - key: GEMINI_API_KEY
        sync: false
      - key: LANGFUSE_HOST
        sync: false
      - key: LANGFUSE_PUBLIC_KEY
        sync: false
      - key: LANGFUSE_SECRET_KEY
        sync: false
      - key: LANGFUSE_TRACING_ENVIRONMENT
        value: render

  - type: web
    name: retrieval
    env: docker
    dockerfilePath: services/retrieval/Dockerfile
    plan: starter         # disks not supported on free
    # healthCheckPath: /
    disk:
      name: faiss-data
      mountPath: /app/data
      sizeGB: 1
    envVars:
      - key: REDIS_URL
        fromService: { type: redis, name: redis, property: connectionString }
      - key: HF_HOME
        value: /app/data/.cache/huggingface
      - key: TRANSFORMERS_CACHE
        value: /app/data/.cache/huggingface/transformers
      - key: HF_HUB_CACHE
        value: /app/data/.cache/huggingface/hub
      - key: HF_DATASETS_CACHE
        value: /app/data/.cache/huggingface/datasets
      - key: SENTENCE_TRANSFORMERS_HOME
        value: /app/data/.cache/huggingface
      - key: FAISS_INDEX_PATH
        value: /app/data/faiss.index
      - key: DOC_MAP_PATH
        value: /app/data/doc_map.json
      - key: VECTOR_STORE
        value: FAISS
      - key: LANGFUSE_HOST
        sync: false
      - key: LANGFUSE_PUBLIC_KEY
        sync: false
      - key: LANGFUSE_SECRET_KEY
        sync: false
      - key: LANGFUSE_TRACING_ENVIRONMENT
        value: render

  - type: web
    name: llm-generate
    env: docker
    dockerfilePath: services/llm_generate/Dockerfile
    plan: free
    # healthCheckPath: /
    envVars:
      - key: REDIS_URL
        fromService: { type: redis, name: redis, property: connectionString }
      - key: GEMINI_API_KEY
        sync: false
      - key: LANGFUSE_HOST
        sync: false
      - key: LANGFUSE_PUBLIC_KEY
        sync: false
      - key: LANGFUSE_SECRET_KEY
        sync: false
      - key: LANGFUSE_TRACING_ENVIRONMENT
        value: render

  - type: web
    name: evaluation
    env: docker
    dockerfilePath: services/evaluation/Dockerfile
    plan: free
    # healthCheckPath: /
    envVars:
      - key: REDIS_URL
        fromService: { type: redis, name: redis, property: connectionString }
      - key: GEMINI_API_KEY
        sync: false
      - key: LANGFUSE_HOST
        sync: false
      - key: LANGFUSE_PUBLIC_KEY
        sync: false
      - key: LANGFUSE_SECRET_KEY
        sync: false
      - key: LANGFUSE_TRACING_ENVIRONMENT
        value: render

  - type: web
    name: api-gateway
    env: docker
    dockerfilePath: services/api_gateway/Dockerfile
    plan: free
    # healthCheckPath: /
    envVars:
      - key: REDIS_URL
        fromService: { type: redis, name: redis, property: connectionString }

      # Set these manually after first deploy (cannot use property: url in Blueprint)
      - key: INGEST_URL
        sync: false
      - key: RETRIEVAL_URL
        sync: false
      - key: EMBEDDINGS_URL
        sync: false
      - key: LLM_GENERATE_URL
        sync: false
      - key: EVALUATION_URL
        sync: false

      - key: STREAMLIT_APP_ORIGIN
        sync: false
      - key: LANGFUSE_HOST
        sync: false
      - key: LANGFUSE_PUBLIC_KEY
        sync: false
      - key: LANGFUSE_SECRET_KEY
        sync: false
      - key: LANGFUSE_TRACING_ENVIRONMENT
        value: render